# Generated by Django 4.2.3 on 2024-01-04 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_remove_wishlist_product_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlist.wishlistitem'),
        ),
    ]
