# Generated by Django 4.2.3 on 2024-01-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_wishlist_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist',
            field=models.ManyToManyField(to='wishlist.wishlistitem'),
        ),
    ]
