# Generated by Django 4.2.3 on 2023-12-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_query_options_query_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='email_address',
            new_name='email',
        ),
    ]
